"""add more tables

Revision ID: 9c2d1a5675a6
Revises: 3b6eed849a95
Create Date: 2023-07-20 22:38:28.480676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c2d1a5675a6'
down_revision = '3b6eed849a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('updated_dtm', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('name')
    )
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_name'), ['name'], unique=True)

    op.create_table('device',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('updated_dtm', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['location.name'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('name', 'location')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_name'), ['name'], unique=True)

    op.create_table('event',
    sa.Column('device', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=True),
    sa.Column('event_dtm', sa.DateTime(), nullable=False),
    sa.Column('updated_dtm', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['action'], ['action.name'], ),
    sa.ForeignKeyConstraint(['device'], ['device.name'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.username'], ),
    sa.PrimaryKeyConstraint('device', 'event_dtm')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_device'), ['device'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_device'))

    op.drop_table('event')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_name'))

    op.drop_table('device')
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_name'))

    op.drop_table('action')
    # ### end Alembic commands ###
